spring:
  application:
    name: x-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/{application}/{profile}

server:
  port: 8763
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}